#Fitness Configuration
#Fri Aug 28 18:41:50 CST 2026
recoveryTime=45
trainingEfficiency=\u654F\u6377\u4F18\u5148
serverRestartTime=16
serverRestartInterval=6
enableAutoEat=true
dropInsteadDestroy=false
enableAutoCaffeine=true
drinkWaterAfter=999
restType=\u5750\u4E0B
accumulatedTrainingMillis=9976958
caffeineMg=133
