#Fitness Configuration
#Fri Aug 28 16:29:37 CST 2026
trainingEfficiency=\u654F\u6377\u4F18\u5148
recoveryTime=45
dropInsteadDestroy=false
enableAutoCaffeine=true
drinkWaterAfter=999
restType=\u5750\u4E0B
accumulatedTrainingMillis=8428297
caffeineMg=133
serverRestartTime=16
serverRestartInterval=6
timePerHit=40
enableAutoEat=true
restAfterHits=3
repairGlovesAfter=5
