#Fitness Configuration
#Thu Aug 27 20:11:35 CST 2026
recoveryTime=40
dropInsteadDestroy=false
enableAutoCaffeine=true
drinkWaterAfter=999
restType=\u5750\u4E0B
accumulatedTrainingMillis=2476457
caffeineMg=133
serverRestartTime=22
serverRestartInterval=6
timePerHit=30
enableAutoEat=true
restAfterHits=3
repairGlovesAfter=5
